<a href="https://colab.research.google.com/github/irythmgarg/Working_with_OrdinalEncoder/blob/main/Working_with_OrdinalEncoder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **WORKING WITH ONEHOTENCODER AND STANDARD SCALER**


In [320]:
import pandas as pd# import pandas class
import numpy as np  #import numpy class

In [321]:
df=pd.read_csv('/content/drug200.csv'); #load dataset
df.head() # first five rows

Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY

In [322]:
df.shape # shape of dataset

(200, 6)

In [323]:
df['Sex'].unique()

array(['F', 'M'], dtype=object)

In [324]:
x=df.iloc[:,0:5]; # independent columns
y=df.Drug; #dependent column
x.head()# first five rows

Age Sex      BP Cholesterol  Na_to_K
0   23   F    HIGH        HIGH   25.355
1   47   M     LOW        HIGH   13.093
2   47   M     LOW        HIGH   10.114
3   28   F  NORMAL        HIGH    7.798
4   61   F     LOW        HIGH   18.043

In [325]:
x.isnull().sum()

Age            0
Sex            0
BP             0
Cholesterol    0
Na_to_K        0
dtype: int64

In [326]:
x.shape

(200, 5)

In [327]:
from sklearn.model_selection import train_test_split # import sklearn train_test_split to train and test
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0) # devide train and test in 80:20
x_train.head() # first five rows

Age Sex    BP Cholesterol  Na_to_K
134   42   F  HIGH        HIGH   21.036
66    29   M  HIGH        HIGH   12.856
26    31   M  HIGH        HIGH   30.366
113   65   F   LOW      NORMAL   13.769
168   51   F   LOW      NORMAL   23.003

In [328]:
y_test.head(10)

18     drugC
170    drugX
107    DrugY
98     DrugY
177    DrugY
182    drugX
5      drugX
146    drugX
12     DrugY
152    drugX
Name: Drug, dtype: object

In [329]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder();
y_train_trans=le.fit_transform(y_train); # apply label encoder on y_train
y_test_trans=le.transform(y_test); # apply label encoder on y_test
y_test_trans[0:10]

array([3, 4, 0, 0, 0, 4, 4, 4, 0, 4])

In [330]:
y_test.head(10)

18     drugC
170    drugX
107    DrugY
98     DrugY
177    DrugY
182    drugX
5      drugX
146    drugX
12     DrugY
152    drugX
Name: Drug, dtype: object

In [331]:
y_train=y_train_trans; # update old object type coulmn of drug to new numerically encoded column
y_test=y_test_trans;# update old object type coulmn of drug to new numerically encoded column
y_test

array([3, 4, 0, 0, 0, 4, 4, 4, 0, 4, 1, 0, 0, 0, 2, 3, 0, 0, 4, 0, 0, 4,
       4, 4, 0, 0, 0, 0, 0, 4, 4, 3, 1, 4, 0, 0, 4, 0, 1, 4])

In [332]:
from sklearn.preprocessing import StandardScaler,OneHotEncoder ,OrdinalEncoder # import standard scaler ,Ordinal Encoder and One Hot Encoder
from sklearn.compose import ColumnTransformer # include column transformer
oe=OneHotEncoder(sparse=False,handle_unknown='ignore') # create a object of onehotencoder
#sparse='False' means not sparse matric formation
#handle unknown =ignore means drop unknown row in test data



In [333]:
len(x_test)

40

In [334]:
x_test.head()

Age Sex      BP Cholesterol  Na_to_K
18    23   M     LOW        HIGH    7.298
170   28   F  NORMAL        HIGH   12.879
107   42   M     LOW        HIGH   20.013
98    20   M    HIGH      NORMAL   35.639
177   25   M  NORMAL        HIGH   19.011

In [335]:
x_train_price=si.fit_transform(x_train_price)
x_test_price=si.transform(x_test_price)
ct=ColumnTransformer([
    ('tnf1',oe,['Sex']),   # apply onehotencoder on one columns
     ('tnf2',OrdinalEncoder(categories=[['LOW','NORMAL','HIGH']]),['BP']),
     ('tnf3',OrdinalEncoder(categories=[['NORMAL','HIGH']]),['Cholesterol']),
     ('tnf4',StandardScaler(),['Na_to_K'])
],remainder='passthrough') # rest columns are as such passed

In [336]:
x_train_trans=pd.DataFrame(ct.fit_transform(x_train)); #. convert it into data from as conlumntransformer make it a numpy array after transformation
x_test_trans=pd.DataFrame(ct.transform(x_test));
len(x_test_trans)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


40

In [337]:
x_test_trans.head()

0    1    2    3         4     5
0  0.0  1.0  0.0  1.0 -1.223470  23.0
1  1.0  0.0  1.0  1.0 -0.446264  28.0
2  0.0  1.0  0.0  1.0  0.547211  42.0
3  0.0  1.0  2.0  0.0  2.723276  20.0
4  0.0  1.0  1.0  1.0  0.407674  25.0

In [338]:
x_test_trans = x_test_trans.rename(columns={
    0: 'Female',
    1: 'Male',
    2: 'BP',
    3: 'Cholesterol',
     4 :'NA_to_K ',
    5: 'Age'
})
x_train_trans = x_train_trans.rename(columns={
    0: 'Female',
    1: 'Male',
    2: 'BP',
    3: 'Cholesterol',
     4 :'NA_to_K ',
    5: 'Age'
})
x_test_trans.head()

Female  Male   BP  Cholesterol  NA_to_K    Age
0     0.0   1.0  0.0          1.0 -1.223470  23.0
1     1.0   0.0  1.0          1.0 -0.446264  28.0
2     0.0   1.0  0.0          1.0  0.547211  42.0
3     0.0   1.0  2.0          0.0  2.723276  20.0
4     0.0   1.0  1.0          1.0  0.407674  25.0

In [339]:
x_train_trans.head()

Female  Male   BP  Cholesterol  NA_to_K    Age
0     1.0   0.0  2.0          1.0  0.689673  42.0
1     0.0   1.0  2.0          1.0 -0.449467  29.0
2     0.0   1.0  2.0          1.0  1.988962  31.0
3     1.0   0.0  0.0          0.0 -0.322323  65.0
4     1.0   0.0  0.0          0.0  0.963596  51.0

In [340]:
from sklearn.linear_model import LogisticRegression # apply logistic regression algorithm as we have classification problem
lr=LogisticRegression(max_iter=1000) #create an object of logistic regression class
lr.fit(x_train_trans,y_train) # fit the training data

LogisticRegression(max_iter=1000)

In [341]:
y_pred=lr.predict(x_test_trans) # predict the test results
y_pred #predicted results

array([3, 4, 0, 0, 0, 4, 4, 4, 0, 4, 1, 0, 0, 0, 2, 3, 0, 0, 4, 0, 0, 4,
       4, 4, 0, 0, 0, 0, 0, 4, 4, 3, 1, 4, 0, 0, 4, 0, 1, 4])

In [342]:
y_test  #actual results

array([3, 4, 0, 0, 0, 4, 4, 4, 0, 4, 1, 0, 0, 0, 2, 3, 0, 0, 4, 0, 0, 4,
       4, 4, 0, 0, 0, 0, 0, 4, 4, 3, 1, 4, 0, 0, 4, 0, 1, 4])

In [343]:
from sklearn.metrics import accuracy_score # accuray score to check accuracy

In [344]:
accuracy_score(y_test,y_pred) # calculate accuracy between real and predicted

1.0

In [345]:
from sklearn.model_selection import cross_val_score # cross val score to check accuracy more than one time

In [346]:
score=np.mean(cross_val_score(lr,x_train_trans,y_train,cv=10)) # means of 10 time accuray to get rid of bias results
score

0.89375